name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER : postgres_user
          POSTGRES_PASSWORD : mysecretpassword
          POSTGRES_DB : pgdb
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
